
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bootstrap-tmax-io-v1alpha1-nodeconfig
  failurePolicy: Fail
  name: vnodeconfig.kb.io
  rules:
  - apiGroups:
    - bootstrap.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodeconfigs
  sideEffects: None
