# permissions for end users to view nodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeconfig-viewer-role
rules:
- apiGroups:
  - bootstrap.tmax.io
  resources:
  - nodeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.tmax.io
  resources:
  - nodeconfigs/status
  verbs:
  - get
