apiVersion: v1
data:
  CACHEURL: http://192.168.111.1/images
  DEPLOY_KERNEL_URL: http://192.168.111.1:6180/images/ironic-python-agent.kernel
  DEPLOY_RAMDISK_URL: http://192.168.111.1:6180/images/ironic-python-agent.initramfs
  DHCP_RANGE: 192.168.111.100,192.168.111.200
  HTTP_PORT: "6180"
  IRONIC_ENDPOINT: http://192.168.111.1:6385/v1/
  IRONIC_FAST_TRACK: "false"
  IRONIC_INSPECTOR_ENDPOINT: http://192.168.111.1:5050/v1/
  PROVISIONING_INTERFACE: eno1
kind: ConfigMap
metadata:
  name: ironic-bmo-configmap-b4mhm66td8
  namespace: metal3
---
apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: mariadb-password-ftkgc8tmkc
  namespace: metal3
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-ironic
  namespace: metal3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metal3-ironic
  template:
    metadata:
      labels:
        name: metal3-ironic
    spec:
      containers:
      - command:
        - /bin/rundnsmasq
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-b4mhm66td8
        image: quay.io/metal3-io/ironic:capm3-v0.3.2
        imagePullPolicy: Always
        name: ironic-dnsmasq
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runmariadb
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-ftkgc8tmkc
        image: quay.io/metal3-io/ironic:capm3-v0.3.2
        imagePullPolicy: Always
        name: mariadb
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runhttpd
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-b4mhm66td8
        image: quay.io/metal3-io/ironic:capm3-v0.3.2
        imagePullPolicy: Always
        name: ironic-httpd
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-ftkgc8tmkc
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-b4mhm66td8
        image: quay.io/metal3-io/ironic:capm3-v0.3.2
        imagePullPolicy: Always
        name: ironic
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-b4mhm66td8
        image: quay.io/metal3-io/ironic-inspector:capm3-v0.3.2
        imagePullPolicy: Always
        name: ironic-inspector
      hostNetwork: true
      initContainers:
      - command:
        - /usr/local/bin/get-resource.sh
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap-b4mhm66td8
        image: quay.io/metal3-io/ironic-ipa-downloader:capm3-v0.3.2
        imagePullPolicy: Always
        name: ironic-ipa-downloader
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      volumes:
      - emptyDir: {}
        name: ironic-data-volume
